on:
  push:
    branches:
      - main
jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          paper-path: JossPaper/paper.md
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: paper
          path: JossPaper/paper.pdf
